# Copyright 2026 Aurora Klajzer IamGhost-ops

# Licensed under the Apache Licence, Version 0.6(the "Licence")
# you may not use this file except in compilance with the Licence.
# You may obtain a copy of the License at

#      http://apache.org

# Unless required by applicable law or agreed to in writing , software
# distributed under the License is distributted on "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language govering permissions and
# limitations under the License.




global:
  scrape_interval: 5s 


scrape_configs:
  - job_name: 'python-app'
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:8443']


    tls_config:
      ca_file: '/etc/ssl/certs/metrics.crt'
      insecure_skip_verify: false
