apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: protect-pods-namespace-escape
  annotations:
    descriptions: "Pods protect"
spec:
  podSelector: {}
  hostSelector: {}
  fentries:
    - call: "__64_sys_setns"
      syscall: true
      args:
        - index: 0
          type: "int"
        - index: 1
          type: "int"
      selectors:
        - matchArgs:
            - index: 1
              operator: "Equal"
              values:
                - "0"

          matchParentBinaries:
            - operator: "In"
              values:
                - "/bin/sh"
                - "/bin/bash"
              followChildren: true

          matchActions:
            - action: Sigkill
